#!/usr/bin/env python
"""
beats.py — beat grid + energy envelope, with no Node and no ffmpeg.

A port of the anime-production skill's extract-beats.mjs onto the numpy +
soundfile path that analyze_reference.py already uses. Same algorithm, same
output schema, so the JSON stays a drop-in for the Remotion pipeline: cuts snap
to beats, flashes fire on downbeats, motion rides the envelope.

Why the port rather than the duplicate it replaces: the .mjs decodes via
ffmpeg, which is not installed here and which the author declined to install.
soundfile bundles libsndfile and reads MP3/FLAC/WAV/OGG directly, so this needs
nothing that analyze_reference.py did not already require. The skill keeps its
own copy — it finds ffmpeg inside Remotion's bundled compositor package — so
the video pipeline is untouched by this.

Output schema (identical to the .mjs):
    source, duration, bpm, offset, beatInterval,
    beats[], downbeats[], onsets[], envelope[], envelopeRate

Note on `bpm`: ACE-Step 1.5 takes bpm as an INPUT, so for tracks generated by
this server you usually already know it — pass `known_bpm` and skip detection
entirely. Detection exists for reference tracks and for anything generated
elsewhere. Worth knowing that the requested bpm and the perceived one can
differ: takes generated at bpm=150 have measured 73.8 here, a half-time feel.
"""

from __future__ import annotations

import json
import os
import sys

import numpy as np
import soundfile as sf

SR = 22050
HOP = 512
WIN = 1024
FRAME_RATE = SR / HOP        # analysis frames per second
ENV_HZ = 30                  # one envelope sample per video frame at 30fps
ONSET_TOLERANCE = 0.06       # seconds; how near an onset must be to count as a hit


def _load_mono(path: str) -> tuple[np.ndarray, float]:
    data, sr = sf.read(path, always_2d=True, dtype="float32")
    mono = data.mean(axis=1)
    dur = len(data) / sr
    if sr != SR:
        n = int(len(mono) * SR / sr)
        mono = np.interp(np.linspace(0, len(mono) - 1, n),
                         np.arange(len(mono)), mono).astype(np.float32)
    return mono, dur


def _frames(x: np.ndarray) -> np.ndarray:
    n = 1 + (len(x) - WIN) // HOP
    if n < 4:
        raise ValueError("clip too short to analyse")
    return np.lib.stride_tricks.as_strided(
        x, shape=(n, WIN), strides=(x.strides[0] * HOP, x.strides[0]))


def analyse(path: str, known_bpm: float | None = None) -> dict:
    x, duration = _load_mono(path)
    fr = _frames(x)
    rms = np.sqrt((fr ** 2).mean(axis=1))
    mag = np.abs(np.fft.rfft(fr * np.hanning(WIN).astype(np.float32), axis=1))

    # --- spectral flux onset envelope ---
    flux = np.maximum(np.diff(mag, axis=0), 0).sum(axis=1)
    flux = np.concatenate([[0.0], flux])
    if flux.max() > 0:
        flux /= flux.max()

    # --- onset picking: local peak above a moving threshold ---
    w = int(FRAME_RATE * 0.25)
    pad = np.pad(flux, (w, w), mode="edge")
    moving = np.array([pad[i:i + 2 * w + 1].mean() for i in range(len(flux))])
    onset_idx = [i for i in range(1, len(flux) - 1)
                 if flux[i] > moving[i] * 1.3
                 and flux[i] >= flux[i - 1] and flux[i] > flux[i + 1]]
    onsets = np.array(onset_idx) / FRAME_RATE

    # --- tempo by autocorrelation of the flux envelope ---
    if known_bpm:
        bpm = float(known_bpm)
    else:
        centred = flux - flux.mean()
        ac = np.correlate(centred, centred, mode="full")[len(centred) - 1:]
        lo, hi = int(FRAME_RATE * 60 / 180), min(int(FRAME_RATE * 60 / 60), len(ac) - 1)
        bpm = 60.0 * FRAME_RATE / (lo + int(np.argmax(ac[lo:hi]))) if hi > lo else 120.0
        while bpm > 170:      # fold absurd tempi into a musical range
            bpm /= 2
        while bpm < 70:
            bpm *= 2

    period = 60.0 / bpm

    # --- phase: slide the grid to whichever offset catches the most onsets ---
    best_off, best_hits = 0.0, -1
    for off in np.arange(0.0, period, 0.005):
        d = np.abs((onsets - off) % period)
        dist = np.minimum(d, period - d)
        hits = int((dist < ONSET_TOLERANCE).sum())
        if hits > best_hits:
            best_hits, best_off = hits, float(off)

    beats = [round(t, 4) for t in np.arange(best_off, duration, period)]
    downbeats = beats[::4]

    env_len = int(duration * ENV_HZ)
    rmax = rms.max() if rms.size and rms.max() > 0 else 1.0
    idx = np.minimum((np.arange(env_len) / ENV_HZ * FRAME_RATE).astype(int), len(rms) - 1)
    envelope = [round(float(v), 3) for v in (rms[idx] / rmax)]

    return {
        "source": os.path.basename(path),
        "duration": round(duration, 3),
        "bpm": round(bpm, 2),
        "offset": round(best_off, 4),
        "beatInterval": round(period, 4),
        "beats": beats,
        "downbeats": downbeats,
        "onsets": [round(float(t), 3) for t in onsets],
        "envelope": envelope,
        "envelopeRate": ENV_HZ,
    }


def write(path: str, out_path: str, known_bpm: float | None = None) -> dict:
    out = analyse(path, known_bpm)
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(out, f, indent=2)
    return out


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("usage: beats.py <audio> [--out beats.json] [--bpm N]")
        sys.exit(2)
    args = sys.argv[1:]

    def _flag(name, cast, default=None):
        return cast(args[args.index(name) + 1]) if name in args else default

    src = args[0]
    dest = _flag("--out", str, os.path.splitext(src)[0] + "_beats.json")
    result = write(src, dest, _flag("--bpm", float))
    print(f"  BPM {result['bpm']}  offset {result['offset']}s  "
          f"{len(result['beats'])} beats, {len(result['onsets'])} onsets")
    print(f"wrote {dest}")
