"""Generate a choice screen's option data from the author's docx.

    python sync_cards.py <master.docx> <game-dir> [cards.json]

WHY THIS EXISTS
---------------
A choice presented as cards -- art, a title, a paragraph of description --
needs that text inside a `screen`, and text inside a screen is invisible to
script_diff, which only compares the narration blocks under scenes/. Writing
the copy into the screen by hand therefore creates a SECOND master: the author
edits the document, nothing reports a difference, and the game keeps showing
the old wording until somebody notices by eye.

That is the one thing this whole setup exists to prevent, so the copy is
generated instead. The author edits the docx; this writes the .rpy.

⚠ THE OUTPUT IS GENERATED. Do not hand-edit it -- rerun this instead.

THE REGION
----------
Card copy is not prose, so it lives in the docx among the author's notes to the
implementer, inside the same span that patterns.json already marks as spec.
This reads that span: it starts at `start` and ends at `end`, and inside it a
SHORT line is a card title and the long line after it is that card's body.
Blank-ish lines and anything parenthesized are skipped, so the author's own
notes can sit in the same block without becoming card text.

cards.json supplies the region markers and the per-card keys, because both are
story content and cannot live in this file:

    {
      "start": "^Prompt:",
      "end":   "^\\\\(after",
      "prompt_from_start": true,
      "cards": [
        {"key": "alpha", "image": "manual alpha"},
        {"key": "beta",  "image": "manual beta"}
      ]
    }

The Nth title/body pair found in the region is matched with the Nth entry in
`cards`, so the ORDER in the document is the order on screen. A mismatch in
count is a hard error rather than a silent truncation -- a card quietly missing
its description is exactly the failure this file is meant to end.
"""
import io
import json
import os
import re
import sys

SHORT = 60          # a line this short inside the region is a title, not a body


def load_cfg(path):
    with io.open(path, encoding="utf-8") as f:
        return json.load(f)


def read_region(docx_path, cfg):
    import docx
    start = re.compile(cfg["start"])
    end = re.compile(cfg["end"])
    rows, inside, pending = [], False, None
    for p in docx.Document(docx_path).paragraphs:
        t = p.text.strip()
        if not t:
            continue
        if not inside:
            if start.match(t):
                inside = True
                if cfg.get("prompt_from_start"):
                    # The heading is the remainder of the start line, after the
                    # marker -- "Prompt: Which one?" yields "Which one?".
                    rows.append(("__prompt__", start.sub("", t).strip()))
            continue
        if end.match(t):
            break
        if t.startswith("("):
            continue
        if len(t) <= SHORT:
            pending = t
        elif pending is not None:
            rows.append((pending, t))
            pending = None
    return rows


def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main():
    if len(sys.argv) < 3:
        sys.exit("usage: python sync_cards.py <master.docx> <game-dir> "
                 "[cards.json]\nPaths are deliberately not stored in this "
                 "repository.")
    docx_path, game = sys.argv[1], sys.argv[2]
    cfg_path = sys.argv[3] if len(sys.argv) > 3 else os.path.join(game, "cards.json")
    if not os.path.exists(cfg_path):
        sys.exit("No card config at %s -- see the module docstring." % cfg_path)
    cfg = load_cfg(cfg_path)

    rows = read_region(docx_path, cfg)
    prompt = ""
    if rows and rows[0][0] == "__prompt__":
        prompt = rows.pop(0)[1]

    want = cfg["cards"]
    if len(rows) != len(want):
        sys.exit("Found %d title/body pairs in the document but cards.json "
                 "lists %d. The region markers or the document have moved; "
                 "refusing to write a partial screen.\nFound: %s"
                 % (len(rows), len(want), [r[0] for r in rows]))

    out = [
        "# GENERATED by tools/sync_cards.py from the author's docx.",
        "# Do not hand-edit -- rerun the tool. The document is the master;",
        "# this file only carries what the choice screen has to display.",
        "",
        "define CARD_PROMPT = _(\"%s\")" % esc(prompt),
        "",
        "define CARDS = [",
    ]
    for (title, body), spec in zip(rows, want):
        out += [
            "    {",
            '        "key": "%s",' % spec["key"],
            '        "image": "%s",' % spec["image"],
            '        "name": _("%s"),' % esc(title),
            '        "desc": _("%s"),' % esc(body),
            "    },",
        ]
    out += ["]", ""]

    dest = os.path.join(game, "cards_generated.rpy")
    io.open(dest, "w", encoding="utf-8", newline="\n").write("\n".join(out))
    print("wrote %s" % dest)
    print("  prompt: %s" % prompt)
    for (title, body), spec in zip(rows, want):
        print("  %-14s %-28s %d chars" % (spec["key"], title, len(body)))
    longest = max(len(b) for _, b in rows)
    print("\nlongest description: %d characters -- a fixed-height card must "
          "still clear it." % longest)
    return 0


if __name__ == "__main__":
    sys.exit(main())
